# Generated by Django 4.2.21 on 2025-05-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userpreference_max_annual_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='auction_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
