# Generated by Django 4.2.21 on 2025-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_opportunity_auction_date_opportunity_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='has_spare_key',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='require_spare_key',
            field=models.BooleanField(default=False, help_text='Only show vehicles that have a spare key'),
        ),
    ]
