# Generated by Django 4.2.21 on 2025-05-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionsite',
            name='scraper_class',
            field=models.CharField(choices=[('SMDScraper', 'SMD Auctions'), ('BidvestScraper', 'Bidvest Auctions'), ('AuctionNationScraper', 'Auction Nation'), ('GoBidScraper', 'GoBid.co.za'), ('WeBiddingScraper', 'WeBidding.co.za'), ('AllSurplusScraper', 'AllSurplus South Africa')], default='SMDScraper', max_length=100),
        ),
    ]
