# Generated by Django 4.2.21 on 2025-05-13 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapers', '0002_alter_auctionsite_scraper_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scraping_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
